name = "default-server"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "566929050a9fafa3a9f2b3985fd52b40aa8b99aafdd5f385eb990bb698b52e10"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
