name = "default-server"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24a8ba16e71c1318693f274bcf7ba4e8ef8fcd8849597b1566b9860c8e68d092"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
