name = "default-server"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f839294ad3baec5638ce17087610147d3be2130d6115a3c115f64586ec9e7aa8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
